top_srcdir   = /home/lind/lind_project/tests/test_cases/httpd
top_builddir = /home/lind/lind_project/tests/test_cases/httpd
srcdir       = /home/lind/lind_project/tests/test_cases/httpd/os
builddir     = /home/lind/lind_project/tests/test_cases/httpd/os
VPATH        = /home/lind/lind_project/tests/test_cases/httpd/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
