top_srcdir   = /home/lind/lind_project/tests/test_cases/httpd
top_builddir = /home/lind/lind_project/tests/test_cases/httpd
srcdir       = /home/lind/lind_project/tests/test_cases/httpd/modules/dav/lock
builddir     = /home/lind/lind_project/tests/test_cases/httpd/modules/dav/lock
VPATH        = /home/lind/lind_project/tests/test_cases/httpd/modules/dav/lock
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
