top_srcdir   = /home/neel/lind_project/tests/test_cases/httpd
top_builddir = /home/neel/lind_project/tests/test_cases/httpd
srcdir       = /home/neel/lind_project/tests/test_cases/httpd/server/mpm
builddir     = /home/neel/lind_project/tests/test_cases/httpd/server/mpm
VPATH        = /home/neel/lind_project/tests/test_cases/httpd/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
