top_srcdir   = /home/lind/lind_project/test_cases/httpd
top_builddir = /home/lind/lind_project/test_cases/httpd
srcdir       = /home/lind/lind_project/test_cases/httpd/modules/debugging
builddir     = /home/lind/lind_project/test_cases/httpd/modules/debugging
VPATH        = /home/lind/lind_project/test_cases/httpd/modules/debugging
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
