top_srcdir   = /home/lind/lind_project/tests/test_cases/httpd
top_builddir = /home/lind/lind_project/tests/test_cases/httpd
srcdir       = /home/lind/lind_project/tests/test_cases/httpd/modules/metadata
builddir     = /home/lind/lind_project/tests/test_cases/httpd/modules/metadata
VPATH        = /home/lind/lind_project/tests/test_cases/httpd/modules/metadata

include $(top_srcdir)/build/special.mk

