top_srcdir   = /home/lind/lind_project/tests/test_cases/httpd
top_builddir = /home/lind/lind_project/tests/test_cases/httpd
srcdir       = /home/lind/lind_project/tests/test_cases/httpd/modules/generators
builddir     = /home/lind/lind_project/tests/test_cases/httpd/modules/generators
VPATH        = /home/lind/lind_project/tests/test_cases/httpd/modules/generators

include $(top_srcdir)/build/special.mk

