top_srcdir   = /home/lind/lind_project/test_cases/httpd
top_builddir = /home/lind/lind_project/test_cases/httpd
srcdir       = /home/lind/lind_project/test_cases/httpd/modules/core
builddir     = /home/lind/lind_project/test_cases/httpd/modules/core
VPATH        = /home/lind/lind_project/test_cases/httpd/modules/core

include $(top_srcdir)/build/special.mk

