top_srcdir   = /home/neel/lind_project/tests/test_cases/httpd
top_builddir = /home/neel/lind_project/tests/test_cases/httpd
srcdir       = /home/neel/lind_project/tests/test_cases/httpd/modules/ldap
builddir     = /home/neel/lind_project/tests/test_cases/httpd/modules/ldap
VPATH        = /home/neel/lind_project/tests/test_cases/httpd/modules/ldap
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
