top_srcdir   = /home/lind/lind_project/tests/test_cases/httpd
top_builddir = /home/lind/lind_project/tests/test_cases/httpd
srcdir       = /home/lind/lind_project/tests/test_cases/httpd/modules/proxy
builddir     = /home/lind/lind_project/tests/test_cases/httpd/modules/proxy
VPATH        = /home/lind/lind_project/tests/test_cases/httpd/modules/proxy
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
#SUBDIRS = balancers
include $(top_srcdir)/build/special.mk
