top_srcdir   = /home/neel/lind_project/tests/test_cases/httpd
top_builddir = /home/neel/lind_project/tests/test_cases/httpd
srcdir       = /home/neel/lind_project/tests/test_cases/httpd/modules/loggers
builddir     = /home/neel/lind_project/tests/test_cases/httpd/modules/loggers
VPATH        = /home/neel/lind_project/tests/test_cases/httpd/modules/loggers

include $(top_srcdir)/build/special.mk

