top_srcdir   = /home/neel/lind_project/tests/test_cases/httpd
top_builddir = /home/neel/lind_project/tests/test_cases/httpd
srcdir       = /home/neel/lind_project/tests/test_cases/httpd/modules/echo
builddir     = /home/neel/lind_project/tests/test_cases/httpd/modules/echo
VPATH        = /home/neel/lind_project/tests/test_cases/httpd/modules/echo

include $(top_srcdir)/build/special.mk

