top_srcdir   = /home/lind/lind_project/test_cases/httpd
top_builddir = /home/lind/lind_project/test_cases/httpd
srcdir       = /home/lind/lind_project/test_cases/httpd/modules/mappers
builddir     = /home/lind/lind_project/test_cases/httpd/modules/mappers
VPATH        = /home/lind/lind_project/test_cases/httpd/modules/mappers

include $(top_srcdir)/build/special.mk

