top_srcdir   = /home/neel/lind_project/tests/test_cases/httpd
top_builddir = /home/neel/lind_project/tests/test_cases/httpd
srcdir       = /home/neel/lind_project/tests/test_cases/httpd/os/unix
builddir     = /home/neel/lind_project/tests/test_cases/httpd/os/unix
VPATH        = /home/neel/lind_project/tests/test_cases/httpd/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
