top_srcdir   = /home/lind/lind_project/test_cases/httpd
top_builddir = /home/lind/lind_project/test_cases/httpd
srcdir       = /home/lind/lind_project/test_cases/httpd/modules/aaa
builddir     = /home/lind/lind_project/test_cases/httpd/modules/aaa
VPATH        = /home/lind/lind_project/test_cases/httpd/modules/aaa

include $(top_srcdir)/build/special.mk

