top_srcdir   = /home/lind/lind_project/test_cases/httpd
top_builddir = /home/lind/lind_project/test_cases/httpd
srcdir       = /home/lind/lind_project/test_cases/httpd/modules/cache
builddir     = /home/lind/lind_project/test_cases/httpd/modules/cache
VPATH        = /home/lind/lind_project/test_cases/httpd/modules/cache

include $(top_srcdir)/build/special.mk

