top_srcdir   = /home/neel/lind_project/tests/test_cases/httpd
top_builddir = /home/neel/lind_project/tests/test_cases/httpd
srcdir       = /home/neel/lind_project/tests/test_cases/httpd/modules/arch/unix
builddir     = /home/neel/lind_project/tests/test_cases/httpd/modules/arch/unix
VPATH        = /home/neel/lind_project/tests/test_cases/httpd/modules/arch/unix

include $(top_srcdir)/build/special.mk

